task: 'router'

model_name: "microsoft/phi-3-mini-4k-instruct"

data_set: train

with_quantization: true
quantization_params:
  load_in_4bit: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: True
  bnb_4bit_compute_dtype: "bfloat16"

with_lora: true
lora_params:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules:
    - "o_proj"
    - "qkv_proj"
  bias: null
  task_type: 'CAUSAL_LM'

training_params:
  eval_strategy: "epoch"
  save_strategy: "no"
  learning_rate: 2e-5
  per_device_train_batch_size: 8
  per_device_eval_batch_size:
  num_train_epochs: 1
  weight_decay: 0.01
  logging_steps: 50
  load_best_model_at_end: false
  max_seq_length:
  gradient_accumulation_steps: 1
  warmup_ratio: 0.0
  seed: 42


